# Generated by Django 2.2.9 on 2021-10-06 13:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211006_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='data_agendamento',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
