# Generated by Django 2.2.9 on 2021-10-16 02:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20211010_2315'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='agenda',
            name='dia__gte',
        ),
        migrations.AddConstraint(
            model_name='agenda',
            constraint=models.CheckConstraint(check=models.Q(dia__gte=datetime.datetime(2021, 10, 16, 2, 15, 28, 934197, tzinfo=utc)), name='dia__gte'),
        ),
    ]
