# Generated by Django 2.2.9 on 2021-10-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_agenda_data_agendamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='data_agendamento',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
