# Generated by Django 2.2.9 on 2021-10-06 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20211006_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agenda',
            old_name='horario',
            new_name='horarios',
        ),
        migrations.AlterUniqueTogether(
            name='agenda',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='data_agendamento',
        ),
        migrations.CreateModel(
            name='Consultas',
            fields=[
                ('id_consulta', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('dia', models.DateField()),
                ('horario', models.TimeField()),
                ('data_agendamento', models.DateTimeField(auto_now_add=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Medico')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'unique_together': {('medico', 'dia')},
            },
        ),
    ]
