# Generated by Django 2.2.9 on 2021-10-22 23:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20211020_2047'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='agenda',
            name='dia__gte',
        ),
        migrations.RemoveConstraint(
            model_name='consultas',
            name='dia__gte',
        ),
        migrations.AddConstraint(
            model_name='agenda',
            constraint=models.CheckConstraint(check=models.Q(dia__gte=datetime.datetime(2021, 10, 22, 23, 30, 9, 790528, tzinfo=utc)), name='dia__gte'),
        ),
        migrations.AddConstraint(
            model_name='consultas',
            constraint=models.CheckConstraint(check=models.Q(dia__gte=datetime.datetime(2021, 10, 22, 23, 30, 9, 790528, tzinfo=utc)), name='dia__gte'),
        ),
    ]
