# Generated by Django 2.2.9 on 2021-10-06 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20211006_1611'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agenda',
            options={'ordering': ['dia'], 'verbose_name': 'Agenda', 'verbose_name_plural': 'Agendas'},
        ),
        migrations.AlterField(
            model_name='consultas',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Agenda'),
        ),
    ]
