# Generated by Django 2.2.9 on 2021-10-08 00:04

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20211006_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='horarios',
        ),
        migrations.AddField(
            model_name='agenda',
            name='horarios',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, related_name='_agenda_horarios_+', to='home.Agenda'),
        ),
    ]
