# Generated by Django 2.2.9 on 2021-10-08 00:22

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20211007_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='horarios',
        ),
        migrations.AddField(
            model_name='agenda',
            name='horario',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, related_name='_agenda_horario_+', to='home.Agenda'),
        ),
    ]
