# Generated by Django 2.2.9 on 2021-10-08 00:38

from django.db import migrations, models
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20211007_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horarios',
            fields=[
                ('id_horario', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('hora', models.TimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='agenda',
            name='horas',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, to='home.Horarios'),
        ),
    ]
