# Generated by Django 2.2.9 on 2021-10-08 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20211007_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='horas',
            field=models.ManyToManyField(to='home.Horarios'),
        ),
    ]
