# Generated by Django 2.2.9 on 2021-10-08 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20211007_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='horas',
        ),
        migrations.AddField(
            model_name='agenda',
            name='horas',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
